function M = G5_manobras_def()
% G5_manobras_def — definicao UNICA das 3 manobras da campanha G5
% (doublets SIL x X-Plane, gemeo v1.1). Consumida por G5_sil (lado SIL),
% G5_xp (lado X-Plane) e plot_G5 (figura + metricas) — garantindo por
% construcao que os dois mundos voam EXATAMENTE a mesma manobra.
%
% Convencao dos doublets (blocos Step_*/Step_*2/Step_*3 dos modelos):
%   ref = base + A*(t>=t1) - 2A*(t>=t2) + A*(t>=t3)   (t2=t3=1e9 inerte)
%
% Duracao 110 s: cabe na "bateria" do motor eletrico do XP9
% (~90-150 s de voo motorizado por reload — ver PENDENCIA_MOTOR.md).

T = 110;

M(1) = struct( ...
    'id',      'dblh', ...
    'titulo',  'doublet de altitude (h ±10 m)', ...
    'T',       T, ...
    'h_A',     10,  'h_t',   [10 45 80], ...
    'psi_A',   0,   'psi_t', [5 1e9 1e9], ...
    'VT_delta',0,   'VT_t',  5);

M(2) = struct( ...
    'id',      'dblpsi', ...
    'titulo',  'doublet de proa (ψ ±15°)', ...
    'T',       T, ...
    'h_A',     0,   'h_t',   [10 1e9 1e9], ...
    'psi_A',   15,  'psi_t', [10 45 80], ...
    'VT_delta',0,   'VT_t',  5);

M(3) = struct( ...
    'id',      'missao', ...
    'titulo',  'perfil de missão comprimido (ψ ±5°, h ±5 m)', ...
    'T',       T, ...
    'h_A',     5,   'h_t',   [35 65 95], ...
    'psi_A',   5,   'psi_t', [20 50 80], ...
    'VT_delta',0,   'VT_t',  5);
end
