function ok = xp_activate()
%XP_ACTIVATE Traz a janela do X-Plane 9 para a frente pelo HANDLE do processo.
%
% (2026-09-08) A janela do Plane Maker tambem se chama 'X-System': um
% AppActivate('X-System') com o Plane Maker aberto ativava o PLANE MAKER, e os
% cliques/ESC do xp_reload_acf iam para ele (diálogo Open Aircraft ficava
% aberto no X-Plane e o XPC emudecia). AppActivate(pid) tambem nao bastou;
% o que funcionou foi user32 SetForegroundWindow no MainWindowHandle do
% processo X-Plane precedido de SendKeys('%') (ALT), que libera a troca de
% foco a partir de um processo em segundo plano. Retorna true se o X-Plane
% ficou em foco.
    ps1 = fullfile(tempdir, 'xp_activate.ps1');
    fid = fopen(ps1, 'w');
    fprintf(fid, '%s\n', ...
        '$p = Get-Process X-Plane -ErrorAction Stop | Select-Object -First 1', ...
        'Add-Type -AssemblyName System.Windows.Forms', ...
        'Add-Type @"', ...
        'using System; using System.Runtime.InteropServices;', ...
        'public class WA { [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr h);', ...
        '  [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr h, int n);', ...
        '  [DllImport("user32.dll")] public static extern bool BringWindowToTop(IntPtr h);', ...
        '  [DllImport("user32.dll")] public static extern IntPtr GetForegroundWindow();', ...
        '  [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr h, out uint pid); }', ...
        '"@', ...
        '[System.Windows.Forms.SendKeys]::SendWait("%")', ...
        '[WA]::ShowWindow($p.MainWindowHandle, 9) | Out-Null', ...
        '[WA]::BringWindowToTop($p.MainWindowHandle) | Out-Null', ...
        '[WA]::SetForegroundWindow($p.MainWindowHandle) | Out-Null', ...
        'Start-Sleep -Milliseconds 600', ...
        '$q = 0; [WA]::GetWindowThreadProcessId([WA]::GetForegroundWindow(), [ref]$q) | Out-Null', ...
        'if ($q -eq $p.Id) { Write-Output 1 } else { Write-Output 0 }');
    fclose(fid);
    [st, out] = system(['powershell -NoProfile -ExecutionPolicy Bypass -File "' ps1 '"']);
    ok = st == 0 && str2double(strtrim(out)) == 1;
    if ~ok, warning('xp_activate: X-Plane nao ficou em foco (%s).', strtrim(out)); end
end
